dbt_football_snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake 
      # Connection Credentials
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"

      # Role & Compute Resources
      role: DATA_ENGINEER
      warehouse: DEV_TRANSFORM_WH
      
      # Target Landing Database for Dev
      database: DEV_ANALYTICS
      schema: football

      # Key-Pair setup (No password needed)
      private_key_path: "{{ env_var('PK_PATH') }}"
      private_key_passphrase: "{{ env_var('PK_PASSPHRASE') }}"

      # Optimization settings
      threads: 1
      client_session_keep_alive: False